from pathlib import Path

engine_path = Path("src/engcalc_colab/engine.py")
engine = engine_path.read_text(encoding="utf-8")

import_old = "from .numeric import NumericContext\n"
import_new = "from .matrix_solve import solve_linear_system\nfrom .numeric import NumericContext\n"
assert engine.count(import_old) == 1
engine = engine.replace(import_old, import_new, 1)

old = '''        if name == "solve":\n            self._require_arity(name, node.args, 2, "equation, unknown")\n            unknown_node = node.args[1]\n            if not isinstance(unknown_node, ast.Name):\n                raise EngEvaluationError("solve unknown must be a symbolic identifier")\n            unknown_name = unknown_node.id\n            unknown = self.engine.resolve_symbol(unknown_name)\n            previous = self.symbol_overrides.get(unknown_name)\n            self.symbol_overrides[unknown_name] = unknown\n            try:\n                equation = self.visit(node.args[0])\n            finally:\n                if previous is None:\n                    self.symbol_overrides.pop(unknown_name, None)\n                else:\n                    self.symbol_overrides[unknown_name] = previous\n            if not isinstance(equation, sp.Equality):\n                equation = sp.Eq(equation, 0, evaluate=False)\n            self.display_input = equation\n            solutions = sp.solve(equation, unknown)\n            if len(solutions) == 0:\n                raise EngEvaluationError(f"solve found no solution for {unknown}")\n            if len(solutions) > 1:\n                raise AmbiguousSolveError(\n                    f"solve returned {len(solutions)} solutions for {unknown}; v0.1 requires one"\n                )\n            return solutions[0]\n'''
new = '''        if name == "solve":\n            self._require_arity(name, node.args, 2, "equation, unknown")\n\n            first_value = self.visit(node.args[0])\n            if is_matrix(first_value):\n                rhs_value = self.visit(node.args[1])\n                return solve_linear_system(first_value, rhs_value)\n\n            unknown_node = node.args[1]\n            if not isinstance(unknown_node, ast.Name):\n                raise EngEvaluationError("solve unknown must be a symbolic identifier")\n            unknown_name = unknown_node.id\n            unknown = self.engine.resolve_symbol(unknown_name)\n            previous = self.symbol_overrides.get(unknown_name)\n            self.symbol_overrides[unknown_name] = unknown\n            try:\n                equation = self.visit(node.args[0])\n            finally:\n                if previous is None:\n                    self.symbol_overrides.pop(unknown_name, None)\n                else:\n                    self.symbol_overrides[unknown_name] = previous\n            if not isinstance(equation, sp.Equality):\n                equation = sp.Eq(equation, 0, evaluate=False)\n            self.display_input = equation\n            solutions = sp.solve(equation, unknown)\n            if len(solutions) == 0:\n                raise EngEvaluationError(f"solve found no solution for {unknown}")\n            if len(solutions) > 1:\n                raise AmbiguousSolveError(\n                    f"solve returned {len(solutions)} solutions for {unknown}; v0.1 requires one"\n                )\n            return solutions[0]\n'''
assert engine.count(old) == 1
engine = engine.replace(old, new, 1)
engine_path.write_text(engine, encoding="utf-8")

matrix_solve = '''from __future__ import annotations\n\nimport sympy as sp\nfrom sympy.matrices.exceptions import NonInvertibleMatrixError\n\nfrom .errors import EngEvaluationError\n\n\ndef solve_linear_system(\n    matrix: sp.MatrixBase,\n    rhs: sp.MatrixBase,\n) -> sp.ImmutableMatrix:\n    """Solve an exact square linear system A*x=b and return an immutable column matrix."""\n    if not isinstance(matrix, sp.MatrixBase):\n        raise EngEvaluationError("solve matrix A must be a matrix")\n\n    coefficient_matrix = sp.ImmutableMatrix(matrix)\n    if coefficient_matrix.rows != coefficient_matrix.cols:\n        raise EngEvaluationError("solve matrix A must be square")\n\n    if not isinstance(rhs, sp.MatrixBase) or rhs.cols != 1:\n        raise EngEvaluationError("solve matrix rhs must be a column vector")\n\n    rhs_matrix = sp.ImmutableMatrix(rhs)\n    if rhs_matrix.rows != coefficient_matrix.rows:\n        raise EngEvaluationError("solve matrix rhs row count must match A")\n\n    try:\n        solution = coefficient_matrix.LUsolve(rhs_matrix)\n    except (NonInvertibleMatrixError, ValueError, ZeroDivisionError) as exc:\n        raise EngEvaluationError(\n            "solve matrix system requires a unique solution"\n        ) from exc\n\n    return sp.ImmutableMatrix(solution)\n'''
Path("src/engcalc_colab/matrix_solve.py").write_text(matrix_solve, encoding="utf-8")
